import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import { Menu } from "../components/Menu";
import { FormFields } from "../components/FormFields";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dynamic Form Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*<Header />
      <Menu />*/}
      <FormFields />
    </>
  );
};

export default Home;
