import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import { Menu } from "../components/Menu";
import { FormFields } from "../components/FormFields";
import { Form } from "../components/Form";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dynamic Form Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="md:flex md:items-start mb-6">
        <div className="md:w-1/6">
          <Menu />
        </div>
        <div className="md:w-1/2">
          <FormFields />
        </div>
        <div className="md:w-1/2">
          <Form />
        </div>
      </div>
    </>
  );
};

export default Home;
