import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import { Menu } from "../components/Menu";
import { FormFields } from "../components/FormFields";
import { useSelector, useDispatch } from "react-redux";
import { addFormField, selectForm } from "../slices/formSlice";

const Home: NextPage = () => {
  const form = useSelector(selectForm);
  const dispatch = useDispatch();

  return (
    <>
      <Head>
        <title>Dynamic Form Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*<Header />
      <Menu />*/}
      <FormFields />
    </>
  );
};

export default Home;
